### PR TITLE
anomaly detection docs typo fixes

### PR DESCRIPTION
**Pull request by hkuffel**
## What
Hello! I just noticed some typos on the Anomaly Detection page of your docs, so this PR is just fixes for those typos.

## How
just edits to the doc md file

Exciting product! Looking forward to following your progress

### CODE REVIEW

**Comment by mateuszklimek** [comment]
@hkuffel thanks!

**Comment by hkuffel** [comment]
Amp!

**Comment by hkuffel** [comment]
np!

**Comment by mateuszklimek** [comment]
@hkuffel Btw, did you also had a chance to play and set up data for yourself? Or you are currently more on an observing phase 😄

**Comment by hkuffel** [comment]
Haven't yet, just observing for now!

**Pull request merged**
