### PR TITLE
feat: docs for warns as alerts

### PR DESCRIPTION
**Pull request by famazak**
## What
*Describe what the change is solving*
Updates docs for re_data:show_warns_as_alerts variable proposed in this PR: https://github.com/re-data/dbt-re-data/pull/127

## How
*Describe the solution*
See linked PR for implementation details in the dbt package's repo

### CODE REVIEW

**Comment by famazak** [comment]
@davidzajac1 thanks for getting this merged!  Will this be able to be included in your next release?

**Comment by davidzajac1** [comment]
> @davidzajac1 thanks for getting this merged! Will this be able to be included in your next release?

@famazak no problem! Yes it will be included in the next release along with a few other features/bugs fixes that are in progress

**Comment by mbyrne00** [comment]
Hey @davidzajac1  - is there a release coming soon? Would _love_ to see this feature and notice there hasn't been a release since Dec 2023. Love the project and appreciate the work - just eager 😉

**Comment by davidzajac1** [comment]
> Hey @davidzajac1 - is there a release coming soon? Would _love_ to see this feature and notice there hasn't been a release since Dec 2023. Love the project and appreciate the work - just eager 😉

@mbyrne00 I've been trying to get a big PR with some new features merged and working with all warehouses before the next release but if I can't get that done soon then I'll just release all the changes so far. So yes probably another release in 2 or 3 weeks!

**Pull request merged**
